name: Scrape every 2 minutes
on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python3 src/scraping-job.py
        env:
          IDFM_API_KEY: ${{ secrets.IDFM_API_KEY }}
          MINIO_S3_ENDPOINT: ${{ secrets.MINIO_S3_ENDPOINT }}
          MINIO_ROOT: ${{ secrets.MINIO_ROOT }}
          MINIO_KEY: ${{ secrets.MINIO_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
